version: "3"

services:
  nginx:
    restart: always
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx-certbot.conf:/usr/src/app/nginx/conf.d/default.conf
      - etc-letsencrypt:/etc/letsencrypt/
      - var-www-certbot:/var/www/certbot/
    env_file:
      - .docker.nginx.env
    command: /bin/bash -c "envsubst '$${SERVER_NAME}' < /usr/src/app/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: certonly --reinstall --webroot --webroot-path=/var/www/certbot --email $EMAIL --agree-tos --no-eff-email -d $SERVER_NAME
    # ^ --force-renewal. ^ Need comment the nginx container when renewal certificate
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - var-www-certbot:/var/www/certbot

volumes:
  etc-letsencrypt:
  var-www-certbot:
